DROP TABLE WHITE;
CREATE TABLE WHITE 
(
	NO NUMBER PRIMARY KEY,
	TITLE VARCHAR2(1000),
	CONTENT VARCHAR2(4000),
	POSTDATE TIMESTAMP
);

DROP SEQUENCE WHITE_SEQ;
CREATE SEQUENCE WHITE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '어제의 아침', '만두국', SYSDATE);
INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '어제의 점심', '순두부찌개', SYSDATE);
INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '어제의 저녁', '김밥', SYSDATE);
INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '오늘의 아침', '잡채', SYSDATE);
INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '오늘의 점심', '김치찌개', SYSDATE);
INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '오늘의 저녁', '삼겹살', SYSDATE);
INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '내일의 아침', '된장찌개', SYSDATE);
INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '내일의 점심', '토스트', SYSDATE);
INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '내일의 저녁', '피자', SYSDATE);
INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '모레의 아침', '미역국', SYSDATE);
INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '모레의 점심', '김치국', SYSDATE);
INSERT INTO WHITE VALUES (WHITE_SEQ.NEXTVAL, '모레의 저녁', '굴국', SYSDATE);

SELECT * FROM WHITE;

-- HR 계정 살리기
ALTER USER HR ACCOUNT UNLOCK;
ALTER USER HR IDENTIFIED BY 1111;

DROP TABLE EMP;
CREATE TABLE EMP AS SELECT * FROM HR.EMPLOYEES;

SELECT * FROM EMP;